-- schema will be generated by models - this is for reference

-- psql --u rebel
-- \c survey
-- \dt

CREATE TABLE account (
    id serial UNIQUE NOT NULL,
    firstname varchar(255) NOT NULL,
    lastname varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    priv integer DEFAULT 0,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    primary key (id)
);

CREATE TABLE organisation (
    id serial UNIQUE NOT NULL,
    account varchar(255) NOT NULL,
    account_id integer NOT NULL,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    foreign key (account_id) references account(id),
    primary key (id)
);

CREATE TABLE campaign (
    id serial UNIQUE NOT NULL,
    campaign varchar(255) NOT NULL,
    organisation_id integer NOT NULL,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    foreign key (organisation_id) references organisation(id),
    primary key (id)
);

CREATE TABLE survey (
    id serial UNIQUE NOT NULL,
    survey varchar(255) NOT NULL,
    organisation_id integer NOT NULL,
    questions json,
    -- questions json -- built from question
    status integer NOT NULL DEFAULT 0,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    foreign key (organisation_id) references organisation(id),
    primary key (id)
);

CREATE TABLE question (
    id serial UNIQUE NOT NULL,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    primary key (id)
);

CREATE TABLE answer (
    id serial UNIQUE NOT NULL,
    survey_id integer NOT NULL,
    question_id integer NOT NULL,
    created timestamp DEFAULT now() NOT NULL,
    updated timestamp DEFAULT now() NOT NULL,
    foreign key (question_id) references question(id),
    primary key (id)
);

CREATE TABLE survey_question ( -- many to many
    survey_id integer REFERENCES survey(id),
    question_id integer REFERENCES question(id),
    PRIMARY KEY (survey_id, question_id)
);

-- Data for testing --
